
import random
import math
# Taking lower limit
lower = int(input("Enter Lower limit : "))
 
# Taking upper limit
upper = int(input("Enter Upper limit : "))
 
# generating a random number between the limits
x = random.randint(lower, upper)
print("\nYou have to guess the random integer generated by the computer.\n")
 
# Initializing the number of guesses.
count = 0

while True:
    count += 1
 
    # taking guessing number as input
    guess = int(input("Guess the number : "))
 
    # Condition testing
    if x == guess:
        print("\nCongratulations you did it in ",
              count, " try")
        # Once guessed, loop will break
        break
    elif x > guess:
        print("Your guess is smaller than the number")
    elif x < guess:
        print("Your guess is larger than the number")
 

# The end result.
print("The number is %d" % x)
print("You've guessed in", count, "number of chances")
print("Better Luck Next time!")